"""Workspace domain models (Pydantic, stored in MongoDB)."""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class SkillRadarEntry(BaseModel):
    """A single skill in the radar chart."""
    skill_name: str
    score: float = Field(ge=0, le=10, default=0.0)
    source: str = "resume_claimed"  # resume_claimed | verified | gap_detected
    last_assessed: datetime | None = None
    assess_count: int = 0


class SkillRadar(BaseModel):
    """Complete skill radar for a user."""
    entries: list[SkillRadarEntry] = Field(default_factory=list)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class WeakPoint(BaseModel):
    """An identified knowledge gap."""
    skill_name: str
    severity: str = "medium"  # low | medium | high | critical
    identified_in_session: str | None = None  # session_id
    identified_at: datetime = Field(default_factory=datetime.utcnow)
    description: str = ""
    recommended_action: str = ""
    resolved: bool = False


class SessionRecord(BaseModel):
    """Summary of a completed v2 session."""
    session_id: str
    mode: str
    target_company: str | None = None
    overall_score: float = 0.0
    round_count: int = 0
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.utcnow)


class TrainingPlan(BaseModel):
    """A training plan generated by the planner node."""
    plan_id: str
    mode: str
    target_topics: list[str] = Field(default_factory=list)
    focus_weak_points: list[str] = Field(default_factory=list)
    max_rounds: int = 5
    strategy_notes: str = ""
    created_at: datetime = Field(default_factory=datetime.utcnow)


class UserMeta(BaseModel):
    """User metadata in workspace."""
    user_id: str
    display_name: str = ""
    total_sessions: int = 0
    last_session_at: datetime | None = None
    preferred_mode: str = "technical"
    created_at: datetime = Field(default_factory=datetime.utcnow)
